# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='beachimg',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Beach'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='landscapeimg',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trail',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trailimg',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
