# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20161105_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City'),
        ),
        migrations.AddField(
            model_name='trail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City'),
        ),
    ]
