# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20161105_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beachs', to='places.City'),
        ),
        migrations.AlterField(
            model_name='beach',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='beach',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beach',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beachimg',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landscapes', to='places.City'),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='places.City'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trail',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trailimg',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
