# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20161229_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/cottage')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cottages', to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/police')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/cottage')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/police')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/cottage')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentcars', to='places.City')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('img_refer', models.ImageField(null=True, upload_to='static/img/cottage')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitue', models.FloatField(default=0.0)),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='places.City')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='landscape',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='trail',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='rentcar',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='police',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together=set([('city',)]),
        ),
        migrations.AlterUniqueTogether(
            name='cottage',
            unique_together=set([('city',)]),
        ),
    ]
