# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20170106_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CottageImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/cottage')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('cottage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cottage_imgs', to='places.Cottage')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/hospital')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_imgs', to='places.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/hotel')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_imgs', to='places.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/police')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_imgs', to='places.Police')),
            ],
        ),
        migrations.CreateModel(
            name='RentCarImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/rentcar')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('rentcar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentcar_imgs', to='places.RentCar')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=True)),
                ('image', models.ImageField(null=True, upload_to='static/img/restaurant')),
                ('datestore', models.DateField(default=datetime.date.today)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_imgs', to='places.Restaurant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='restaurantimg',
            unique_together=set([('restaurant',)]),
        ),
        migrations.AlterUniqueTogether(
            name='rentcarimg',
            unique_together=set([('rentcar',)]),
        ),
        migrations.AlterUniqueTogether(
            name='policeimg',
            unique_together=set([('police',)]),
        ),
        migrations.AlterUniqueTogether(
            name='hotelimg',
            unique_together=set([('hotel',)]),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalimg',
            unique_together=set([('hospital',)]),
        ),
        migrations.AlterUniqueTogether(
            name='cottageimg',
            unique_together=set([('cottage',)]),
        ),
    ]
