# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20170111_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='datestore',
        ),
    ]
