# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_remove_beach_datestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='datestore',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
