# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20170111_0050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beach',
            unique_together=set([]),
        ),
    ]
