# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20170111_0328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cottage',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='landscape',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='police',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='rentcar',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='trail',
            unique_together=set([]),
        ),
    ]
