# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20170111_0330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beachimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='cottageimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='hotelimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='landscapeimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='policeimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='rentcarimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantimg',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='trailimg',
            unique_together=set([]),
        ),
    ]
