# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20170111_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='img_refer',
            field=models.ImageField(null=True, upload_to='static/img/beachs'),
        ),
        migrations.AddField(
            model_name='landscape',
            name='img_refer',
            field=models.ImageField(null=True, upload_to='static/img/landscape'),
        ),
        migrations.AddField(
            model_name='trail',
            name='img_refer',
            field=models.ImageField(null=True, upload_to='static/img/trails'),
        ),
    ]
