# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20170111_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beachimg',
            name='beach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Beach'),
        ),
        migrations.AlterField(
            model_name='trailimg',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Trail'),
        ),
    ]
