# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20170121_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottageimg',
            name='cottage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Cottage'),
        ),
        migrations.AlterField(
            model_name='hospitalimg',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Hospital'),
        ),
        migrations.AlterField(
            model_name='hotelimg',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Hotel'),
        ),
        migrations.AlterField(
            model_name='landscapeimg',
            name='landscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Landscape'),
        ),
        migrations.AlterField(
            model_name='policeimg',
            name='police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Police'),
        ),
        migrations.AlterField(
            model_name='rentcarimg',
            name='rentcar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.RentCar'),
        ),
        migrations.AlterField(
            model_name='restaurantimg',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_place', to='places.Restaurant'),
        ),
    ]
