# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_auto_20170121_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='description_en_us',
            field=models.CharField(default='', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='description_es',
            field=models.CharField(default='', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='subtitle_en_us',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='subtitle_es',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beachimg',
            name='description_en_us',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='beachimg',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
